# This is a basic workflow to help you get started with Actions

name: request-activation-file

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  request-activation-file:
    uses: game-ci/unity-request-activation-file@v2.0-alpha-1
